PAPER_IMG_DIR=~/papers/2024-pbml-evaldio/img
#PAPER_IMG_DIR=~/projects/phd/papers/2024-pbml-evaldio/img
PAPER_TABLE_DIR=~/papers/2024-pbml-evaldio/table
#PAPER_TABLE_DIR=~/projects/phd/papers/2024-pbml-evaldio/table

update: update_tables update_figures

update_figures:
	cp figures/*.pdf $(PAPER_IMG_DIR)
update_tables:
	cp tables/*.tex $(PAPER_TABLE_DIR)
